### ISSUE TITLE
Decidim integration spike

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/decidim-instance#2]
On participative process proposals.

Scenarios:
- [x] participant creates delegation
- [x] participant deletes delegation (#7)
- [ ] participant votes (#8)
- [ ] participant removes vote (#9)
- [ ] participant views voting result with the delegations factored in (#10)

**Comment by jinjagit** [comment]
After getting a decidim-instance + consultations + action-delegator running and fully seeded today, we realized a few things re. the imagined coopdevs integration spike:  

### Coopdevs model:  
- Consultations <- Questions <- Responses  
- A vote = selecting a response (presumable an affirmative statement) from a list of responses. Only one response can be selected.
- Delegates (grantees) can cast a different vote (different response) for each vote delegated to them.
- Voting periods have a specified start and end date.

### Implications:
- We could use our API votes with proposal_url == response (Coopdevs)  
- Coopdevs client could count these proposal_url votes at any time to create a voting result (could even use our voting_result to get a total of each response count, but will still need client-side math to get vote result).  
- Could use our delegations model to keep record of each delegation, but unclear if this would be useful or not.  
- Our current delegation model does not permit casting a different vote (different proposal_url on our API side) for each delegation made (our voting system is set up for counting all delegator votes as weights for the single choice of the delegate, not for different choices per delegated vote). We would need a significantly different model of delegations on our API or just implement / use implementation on the Coopdevs client.

**Comment by jinjagit** [comment]
This issue may well have some overlaps with [#9](https://github.com/liquidvotingio/decidim-liquidvoting/issues/9) (Improve UX)
